### ISSUE TITLE
default tree name to come from config, and be changed to Acorn State of Affairs

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn-ui#112]
* default tree name to come from config
`https://github.com/h-be/acorn-ui/blob/master/src/components/Header/Header.js` on line:
`                  <div className='canvas-name'>H-BE SoA</div>`
* default tree should be named "Acorn State of Affairs" (written out) (instead of the current "HBE SoA")

**Comment by Connoropolous** [comment]
will do
