### ISSUE TITLE
clear date doesn't work in DatePicker, because it wasn't wired up

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn-ui#115]
I am referring to "clear all" in this:

<img width="348" alt="Screen Shot 2020-01-31 at 6 45 53 PM" src="https://user-images.githubusercontent.com/1409121/73585821-f9167c80-4459-11ea-8542-4efd6e17f5ce.png">
It wasn't connected to an event listener

**Comment by leruaa** [comment]
@Connoropolous I think it has been fixed, I'm not able to reproduce this bug.

**Comment by Connoropolous** [comment]
No?
I think the nature of it is that it *looks* like it's been cleared, but if you check the places where it shows the dates, it will still have them

**Comment by Connoropolous** [comment]
p.s. thanks for chiming in!
I guess you were testing things out, and checking out the project. 
What's your interest?

**Comment by leruaa** [comment]
Oh you're right ! the "clear all" is not applied when closing the timeframe window.

btw I'm looking for a project to dig into Holochain, acorn looks really interesting!

**Comment by Connoropolous** [comment]
We'd love your help
