### ISSUE TITLE
Card creation issue

### ISSUE THREAD

**Issue by bierlingm** [h-be/acorn-ui#127]
Holding "g" and left-clicking to create a card doesn't work

**Comment by bierlingm** [comment]
So, apparently it's an issue with input detection. I use the Dvorak layout and pressing the button for "g", actually "u" on the physical keyboard, doesn't allow me to create a card. But pressing the physical key "g", which is "i" in Dvorak, allows me to actually create a card.

So my assumption is that it ignores input from keyboard layouts other than the standard physical keyboard.

**Comment by Connoropolous** [comment]
Oh gotcha! That's reaallly good and useful feedback. 

As a dvorak user, what are your general expectations with keyboard shortcuts on platforms, when they use the term "g", you refer to the placement of "g" in the dvorak keyboard layout?

**Comment by bierlingm** [comment]
My general expectation as a Dvorak user is that my keyboard just works, haha... 😆

So yes, I expect "g" to mean "g" in the currently saved keyboard layout.

I never have problems with faulty input detection, since I've changed my keyboard layout on Mac to Dvorak via the System Preferences.

**Comment by Connoropolous** [comment]
of course. 

Early on some developers of Acorn started using a less conventional approach to listening to the keyboard events, and I went along with it not knowing exactly what the implications would be. Now I do, we'll switch it back to the standard, and that will fix that I'm sure.

This issue will become a technical issue for tracking from now on.

Ooo, just discovered this is extremely trivial to fix. 
Will just switch this line from `event.code` to `event.key` and we're golden. MDN docs specifically mention DVORAK and such.
https://github.com/h-be/acorn-ui/blob/master/src/event-listeners/index.js#L57

**Comment by Connoropolous** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
