### ISSUE TITLE
create profile placeholder avatar is broken image

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn-ui#40]
When launching Acorn for the first time, and prompted to create a new profile, the placeholder avatar appears as a broken image.

Looking at the code in `src/components/ProfileEditForm/ProfileEditForm.js`, I wonder if the `if (whoami)` clause which calls `setAvatarUrl(whoami.avatar_url)`, needs an else clause to set a default image URL?

**Comment by Connoropolous** [comment]
yes, that's been bugging Pegah for a while... 

I guess the idea would be that if the field is empty, then it can show a default one, but if you fill something in and it's an invalid url it could still display that broken image, to give you the feedback that the image doesn't exist

**Comment by Connoropolous** [comment]
thanks for logging! please log other things if they arise through use

**Comment by Connoropolous** [comment]
#usertesting

**Comment by samcooley** [comment]
@pegahvaezi, I think this was fixed by introducing the default initials (text) avatar, is that right? can we/you close this issue? (please do link to a pull request if easy to identify)

**Comment by Connoropolous** [comment]
Yeah, I'd say that's true. 
Closed by this PR: https://github.com/h-be/acorn-ui/pull/109
